### ISSUE TITLE
32-bit + FP on mac seems broken

### ISSUE THREAD

**Issue by tommythorn** [im-tomu/fomu-toolchain#13]
I've done no triage yet, but wanted to record it before I run out of time.

Installed the (latest) 1.5.3 release on macOS (10.15.2)
```
$ echo -e '#include<stdio.h>\nint main(int c,char **v){printf("Hello World!\\n");return 0;}' > hw.c
$ riscv64-unknown-elf-gcc -mabi=ilp32 -march=rv32gc ~/hw.c -o hw.elf
/fomu-toolchain-macos-v1.5.3/bin/../lib/gcc/riscv64-unknown-elf/8.3.0/../../../../riscv64-unknown-elf/bin/ld: /fomu-toolchain-macos-v1.5.3/bin/../lib/gcc/riscv64-unknown-elf/8.3.0/../../../../riscv64-unknown-elf/lib/crt0.o: ABI is incompatible with that of the selected emulation:
...
```

Looks like it's trying to link again 64-bit versions of the library.

Note, all variations of -march=rv32XX without f and g works as expected.

**Comment by xobs** [comment]
Fomu's core has no floating point unit, so `f` and `g` will generate illegal instructions.

**Comment by tommythorn** [comment]
Yes, but I'm not using Fomu's core.  Regardless, I had time to look into this and the problem comes straight from SiFive and is even present in their latest tool drop.  It's fine they don't support it, but the failure could have been more obvious.

Thanks

**Comment by xobs** [comment]
Is it fixed if you use https://github.com/xpack-dev-tools/riscv-none-embed-gcc-xpack, by any chance?

**Comment by tommythorn** [comment]
I tested it and AFAICT it doesn't misbehave the same way on enabling FP.  I can't tell for sure because it doesn't include libgloss and thus fails on anything using stdio.
