### ISSUE TITLE
Update the wishbone tool

### ISSUE THREAD

**Issue by lromor** [im-tomu/fomu-toolchain#14]
Hi,

I'm playing with fomu, specifically I added:
https://github.com/im-tomu/foboot/blob/master/hw/rtl/sbwarmboot.py
to my SoC. I'm using the Wishbone Tool 0.4.7 to reboot the fomu without re-plugging it.
If I send the reboot command with this version, the wishbone-tool starts polling:
```
ERROR [wishbone_tool::bridge::usb] unexpected bridge poke response: Some(OpenedDevice)
INFO [wishbone_tool::bridge::usb] waiting for target device
INFO [wishbone_tool::bridge::usb] opened USB device device 023 on bus 002
ERROR [wishbone_tool::bridge::usb] unexpected bridge poke response: Some(OpenedDevice)
INFO [wishbone_tool::bridge::usb] waiting for target device
```
I noticed that the problem with Wishbone Tool 0.6.9 completely disappears.
Would it be a problem for you to update the release version of:
https://github.com/im-tomu/fomu-toolchain/blob/master/build.sh#L6

**Comment by mithro** [comment]
@xobs - How do we do this?

**Comment by xobs** [comment]
Good call!  I just updated it in `build.sh` and v1.5.4 should be ready soon.
