### ISSUE TITLE
Upgrade nextpnr-ice40 to current version for significant build speed improvements

### ISSUE THREAD

**Issue by elecbrick** [im-tomu/fomu-toolchain#15]
I was struggling with 8 to 12 hour build times for a design which utilizes 95% of the device. The variance was for different seeds, most of which would fail to meet timing once routing was complete. Simply replacing this one executable from the v1.5.3 release a Mar 13 snapshot decreased my build time to 5 minutes and timing is now consistently being met. This is a 100x speedup.

As a side effect, the improved placing also cures https://github.com/im-tomu/foboot/issues/45

**Comment by xobs** [comment]
Does v1.5.6 solve the issue? https://github.com/im-tomu/fomu-toolchain/releases/tag/v1.5.6

**Comment by elecbrick** [comment]
Yes, initial testing has confirmed this 20x faster routing that the previous version. My test was with unmodified foboot and with a custom version that utilizes 95% of the LC blocks. The significant change appears to be replacing the choice of algorithmic OR simulated annealing placing with two passes that first use HeAP smart placing followed by simulated annealing for refinement. This results in significantly easier and thus faster routing.

I forgot to mention that my testing was on a straight pull of foboot and litex dated Feb 2 running the Linux tools.
