### ISSUE TITLE
nextpnr-ice40 crashes

### ISSUE THREAD

**Issue by AnttiLukats** [im-tomu/fomu-toolchain#2]
as title, nextpnr-ice40 just crashes on win...

**Comment by xobs** [comment]
Do you have more information?  Are you running on 32-bit Windows?  What happens if you double-click the exe rather than running it from a terminal?

**Comment by AnttiLukats** [comment]
w64 w7, I am starting all things from FAR commander as Norton Commander is now longer avail, so I only press enter on the EXE files to execute them

**Comment by xobs** [comment]
If you double-click on the program instead of running it from the console, it will tell you about any missing dependencies.

**Comment by xobs** [comment]
Please reopen this issue if you have any further information.
