### ISSUE TITLE
Support for iCEBreaker/WTFpga

### ISSUE THREAD

**Issue by drayde** [im-tomu/fomu-toolchain#8]
Would be awesome if one could use this great toolchain build for the iCEBreaker FPGA board as well. Also, that would enable the WTFgpa workshops/tutorial to support Windows users, who are currently left out due to installation being to complicated.

The only thing that needs to be done to support iCEBreaker is to (re-)include iceprog. Everything else is already there. Also, WTFpga only needs the addition of iceprog, no extra tools.

**Comment by drayde** [comment]
It got it working for Windows and Linux in a fork already (not tested though)
See https://github.com/drayde/toolchain-icestorm/tree/icebreaker-support and https://travis-ci.org/drayde/toolchain-icestorm/builds/588034375
In case there is interest to include this, I can try to get it working for macosx as well

**Comment by xobs** [comment]
I can add it, if you like.  I know that when I tried it on Windows with an icebreaker, I had no end of trouble and ended up just using the Lattice tools.  But if you want wecan merge it.  I agree having a precompiled toolchain is super helpful.

**Comment by drayde** [comment]
At least the WTFpga examples work without issues in Windows with just adding iceprog. Haven't tested more yet (I'm an FPGA beginner :-))
OK, I'll work on the macosx part and prepare an PR for you.
One question: where do the packages in build-data/darwin come from? I need to add libftdi

**Comment by xobs** [comment]
Those packages all come from conda -- I was using homebrew originally, but homebrew takes 10 minutes just to start on Travis-CI, and doesn't include static packages.  https://anaconda.org/conda-forge/

**Comment by drayde** [comment]
OK, took a while (needed to create my own libftdi conda package, there was none for osx), but it now compiles for all platforms:
https://github.com/drayde/toolchain-icestorm/releases/tag/test001
I also prepared full packages for testing:
https://github.com/drayde/fomu-toolchain/releases/tag/test001
Windows seems to work fine, linux and osx ist not tested yet. I'll look for people helping me testing (I don't have osx) and get back to you.
Of course, you can have a look at it already as well, @xobs ;-)

**Comment by pcossutta** [comment]
@drayde I tested in macOS Mojave (10.14.6) on a MacBook Air (13-inch, Mid 2013) and it works as expected.

**Comment by drayde** [comment]
Awesome, thx for testing, @pcossutta !!
Still didn't get around testing it on a minimal Linux system, when I have done that I'll create the PR

**Comment by drayde** [comment]
Added a PR in toolchain-icestorm for this.
See https://github.com/xobs/toolchain-icestorm/pull/1

**Comment by xobs** [comment]
v1.5.3 has been released now, which includes the iceprog!

There was a v1.5.2 which was released, but the Windows build was broken.  Please see if v1.5.3 works for you and update this issue accordingly.

**Comment by drayde** [comment]
Great! Tested the Windows builds, works fine. Closing the issue. Thx!
