### ISSUE TITLE
python3 missing setuptools 

### ISSUE THREAD

**Issue by jnsquire** [im-tomu/fomu-toolchain#9]
The fomu-workshop docs suggest running 'python3 workshop.py --board hacker' from the litex directory of the workshop repo. Doing so results in an exception due to missing the 'distutils.spawn' import, because python3 is picked up from the fomu-toolchain bin directory, and this is apparently missing the setuptools package. Running with the system python3 works OK. Seems like either the locally installed python3 should be removed, or setuptools included.

**Comment by xobs** [comment]
That depends on the platform you're using.  Python packaging is a mess.

On Windows, we use python from python.org, which doesn't include setuptools, pip, or anything like that.  I'm not sure why they don't ship with it, so I assume seutptools is not officially supported.

On Darwin we ship the Conda python, which also might not include it by default.

On Linux we don't ship Python.

As a result of this mess, the `workshop.py` project doesn't use any sort of python packaging or modules.  Instead it sets PYTHONPATH to the various subdirectories under `deps/`.  What does the trace show you when you try to build `workshop.py`?

**Comment by jnsquire** [comment]
The 1.4 toolchain package for Linux includes python in bin/

Here's the output from a fresh Ubuntu 19.10 installation, with jus the toolchain bin directory added to $PATH:

joel@joel-VirtualBox:~/fomu-workshop/litex$ python3 workshop.py --board pvt
lxbuildenv: v2019.8.19.1 (run workshop.py --lx-help for help)
lxbuildenv: Skipping git configuration because "skip-git" was found in LX_CONFIGURATION
lxbuildenv: To fetch from git, run workshop.py --board pvt --lx-check-git
Traceback (most recent call last):
  File "workshop.py", line 57, in <module>
    main()
  File "workshop.py", line 46, in main
    soc = BaseSoC(args.board, pnr_seed=args.seed, pnr_placer=args.placer, usb_bridge=True)
  File "/home/joel/fomu-workshop/litex/deps/litex_boards/litex_boards/partner/targets/fomu.py", line 158, in __init__
    from litex_boards.partner.platforms.fomu_pvt import Platform
  File "/home/joel/fomu-workshop/litex/deps/litex_boards/litex_boards/partner/platforms/__init__.py", line 1, in <module>
    from litex_boards.partner.platforms import aller
  File "/home/joel/fomu-workshop/litex/deps/litex_boards/litex_boards/partner/platforms/aller.py", line 6, in <module>
    from litex.build.xilinx import XilinxPlatform
  File "/home/joel/fomu-workshop/litex/deps/litex/litex/build/xilinx/__init__.py", line 1, in <module>
    from litex.build.xilinx.platform import XilinxPlatform
  File "/home/joel/fomu-workshop/litex/deps/litex/litex/build/xilinx/platform.py", line 8, in <module>
    from litex.build.xilinx import common, vivado, ise
  File "/home/joel/fomu-workshop/litex/deps/litex/litex/build/xilinx/vivado.py", line 8, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils.spawn'
joel@joel-VirtualBox:~/fomu-workshop/litex$ which python3
/home/joel/fomu-toolchain-linux_x86_64-v1.4/bin/python3

**Comment by xobs** [comment]
It looks like there's an upstream bug in `litex_boards` that's causing it to import some Xilinx code, which is where the problem is.

Does it work if you do "git submodules sync"?

**Comment by jnsquire** [comment]
No, same issue. It does seem that having litex_boards.partner.platforms.__init__ import *all* the platforms is a bit of a questionable choice.

**Comment by xobs** [comment]
So, weirdly, that doesn't exist in the current version, so maybe the issue is that it was the case in a previous version and it hasn't been updated.  https://github.com/litex-hub/litex-boards/commit/b4eefa6c33ca6a8047da7cafc777d4caa254a34e#diff-51bb6e3c520ff0f217d38140b3a39ae8

What happens if you do `git -C deps/litex_boards checkout origin/master`?

**Comment by jnsquire** [comment]
Yep, that fixes things up nicely.

**Comment by xobs** [comment]
I updated it in e64417cfb124f39e12cda297e48586120f2e412c

I'm still working on getting a version of Python with setuptools, but at least this should be enough to get you going.
